### ISSUE TITLE
Login Seite bleibt stehen

### ISSUE THREAD

**Issue by tobias-lambrecht** [pluginkollektiv/2-Step-Verification#11]
In einigen Fällen bleibt bei einer Multisite / Multilingual Press / Jigoshop Installation die Login Seite hängen. Der Code kommt dann per Mail, es erscheint jedoch kein Eingabefenster.

Warum es mal tut und warum nicht kann ich noch nicht näher eingrenzen. Credentials für das Testsystem kann ich dir gerne zur Verfügung stellen.

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
