### ISSUE TITLE
Fehlermeldung bei abgelaufenem Sicherheitscode erstellen

### ISSUE THREAD

**Issue by PixelbarEupen** [pluginkollektiv/2-Step-Verification#12]
Habe den Sicherheitscode gerade mal ablaufen lassen und dann eingegeben. Die Seite lädt einfach neu und man landet wieder beim wp-login.php Screen.

Wäre es nicht sinnvoll noch eine Fehlermeldung à la "Der Sicherheitscode ist abgelaufen, Sie werden nun zum Anmeldebildschirm geleitet." zu erstellen?

Das selbe gilt für falsch eingegebene Sicherheitscodes. Man erhält keine Fehlermeldung sondern das Feld leert sich einfach.

**Comment by 00travelgirl00** [comment]
Man könnte ja auch eine neutralen Hinweis geben, der keinen Rückschluss auf das Problem gibt. 

"Oops Something went wrong! You will be redirect to the login page"

oder sowas in der Art.

**Comment by 2ndkauboy** [comment]
Wie wäre es mit dieser Darstellung:

![image](https://user-images.githubusercontent.com/1793177/45822727-648bfe00-bcec-11e8-8a6f-ad1c684b4ce8.png)

**Comment by 2ndkauboy** [comment]
Noch besser würde ich es finden, wenn wir nicht selbst ein eigenes Mini-Template laden, sondern die `wp-admin.php` mit einer eigenen `action` aufrufen und dann unser Formular laden. Das Feature-Plugin `two-factor` macht dies auch und dort sieht das Formular wie folgt aus:

![image](https://user-images.githubusercontent.com/1793177/45822842-99985080-bcec-11e8-88e8-cf100e3fdeb6.png)

**Comment by 2ndkauboy** [comment]
FYI: Das ist die aktuelle Ansicht des Formulars:

![image](https://user-images.githubusercontent.com/1793177/45822893-c0ef1d80-bcec-11e8-8e55-56c5cee15a07.png)

**Comment by Zodiac1978** [comment]
Ich vote für den Core-Weg. Aufruf der Seite mit action, so wie bei dem Feature-Plugin.

**Comment by 2ndkauboy** [comment]
Danke für das Feedback. Dann muss ich wohl nochmal komplett neu ran ;)

**Comment by 2ndkauboy** [comment]
Hm, die Art und Weise, wie es das Feature-Plugin macht ist ziemlich unsauber und echt umfangreich (sie kopieren Teile von Core-Funktionen, damit sie das Aussehen des wp-login.php erreichen, brechen das Rendering dann aber hart ab).

Ich würde also empfehlen, dass wir mit dem eigenen Template weiterarbeiten, mit den entsprechenden Anpassungen aus dem Branch.

**Comment by Zodiac1978** [comment]
Wenn das vom Aussehen und Verhalten auf das Gleiche herauskommt ist mir das ebenso Recht :)

**Comment by 2ndkauboy** [comment]
Abgesehen vom WordPress-Logo und den zwei zusätzlichen Links sieht das Formular, der Button und die Hinweis- und Fehlermeldungen genau so aus, wie man es vom Login-Formular gewohnt ist. Das hier wäre der aktuelle neue Stand: https://github.com/pluginkollektiv/2-Step-Verification/issues/12#issuecomment-423189309

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
