### ISSUE TITLE
Neuer Login sperrt gesamtes Konto bis verifiziert wurde

### ISSUE THREAD

**Issue by PixelbarEupen** [pluginkollektiv/2-Step-Verification#13]
Es kommt häufig vor, dass mehrere Benutzer das selbe Konto nutzen. Ist User A eingeloggt und User B möchte sich ebenfalls einloggen, erscheint auch bei User A die Codeverifizierung, sobald er im Backend klickt. Dieser muss dann darauf hoffen, dass User B sich zügig einloggt um weitermachen zu können.

Wenn User A beispielsweise gerade einen Beitrag veröffentlichen will ist das sehr ärgerlich.

Dieses Szenario geht zwar schon recht weit aber ich denke, man sollte es nicht ausser acht lassen? Eure Meinung?

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
