### ISSUE TITLE
Plugin generiert Sicherheitscodes, die nicht benötigt werden (WordPress-App / Anmelde-Overlay)

### ISSUE THREAD

**Issue by joschuba** [pluginkollektiv/2-Step-Verification#14]
Wenn ich in der Android-WordPress-App in der Navigation den Punkt „Seite ansehen“ wähle, bekomme ich eine Mail mit einem Sicherheitscode zugestellt, den ich ja aber nicht brauche, da ich ja erstens in der App bin und mir zweitens nur das Frontend ansehe. Kannst du da irgendwie eingreifen?

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
