### ISSUE TITLE
Redirect auf Frontend nach Anmeldung verschiebt 2fa

### ISSUE THREAD

**Issue by hostz-frank** [pluginkollektiv/2-Step-Verification#15]
Wenn eine Site nur angemeldeten Usern zugänglich sein soll und nach dem Login auf den Content redirected wird, wird der zweite Schritt der Authentifizierung nicht mehr sichtbar. Geht dann aber ein User z.B. in sein Profil irgendwann, wirkt die plötzliche Abfrage nach dem Code  1.) unlogisch und 2.) der Code kann auch schon abgelaufen sein.

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
