### ISSUE TITLE
Multisite Authentifizierung

### ISSUE THREAD

**Issue by hostz-frank** [pluginkollektiv/2-Step-Verification#16]
Wenn ein User auf mehrere Sites eines Netzwerks Zugriff hat, bleibt er beim Wechsel der Site gewöhnlich authentifiziert. Dies scheint 2-Step-Verification nicht zu berücksichtigen. Hier wird plötzlich mehrmaliges 2-stufiges Anmelden notwendig.

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
