### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by StephanieWiermann** [pluginkollektiv/2-Step-Verification#20]
# Plugin Name

Contributors:      pluginkollektiv
Donate link:       https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=LG5VC9KXMAYXJ
Tags:              … tags …
Requires at least: … minimum WP version …
Tested up to:      … latest WP version …
Stable tag:        trunk
License:           GPLv2 or later
License URI:       http://www.gnu.org/licenses/gpl-2.0.html
### Credits

Author: Sergej Müller Maintainers: pluginkollektiv

**Comment by bueltge** [comment]
Merged with #29/#30 Thx. @StephanieWiermann
