### ISSUE TITLE
An welche Adresse wird die Mail versendet

### ISSUE THREAD

**Issue by mario1michel** [pluginkollektiv/2-Step-Verification#22]
Hallo,
ich habe eine Frage zum Versand der Mail.
An welche hinterlegte Adresse bzw. in welchen Menue hinterlegte Adresse wird die Mail versand?
Ich hatte das Plugin installiert, vorher die Adresse des Benutzers nochmalig geprüft, aber es kommt keine Mail.

Welche Datei auf dem Backend muss gelöscht werden um erneueut auf dieses zu kommen und erneut die Einstellungen vorzunehmen?

**Comment by 2ndkauboy** [comment]
Die E-Mail wird an die Adresse des Nutzers aus seinem Profil verschickt. Ich konnte mit der aktuellen Version keinen Fehler feststellen. Bist du dir sicher, dass deine WordPress Installation überhaupt E-Mails verschicken kann? Teste das am besten mal, indem du die "Passwort vergessen?" Funktion benutzt.

Um das Plugin zu deaktivieren, benenne einfach den Order `wp-content/plugins/2-Step-Verification` um oder lösche ihn.
