### ISSUE TITLE
Seit WP 4.6 keine Funktion mehr?

### ISSUE THREAD

**Issue by Martin597** [pluginkollektiv/2-Step-Verification#24]
Seit WordPress 4.6 geht das Plugin bei mir nicht mehr. Und zwar in allen WP-Installationen. Es wird keine Passwort-Mail mehr verschickt. Ist das Problem bekannt bzw. gibt es eine Lösung?

**Comment by swissspidy** [comment]
Hallo Martin

Das liegt viel eher an einem [Bug in WordPress](https://core.trac.wordpress.org/ticket/37736) als einem Fehler im Plugin. Auf einigen System schickt WordPress deshalb keine E-Mails mehr. Dieser Fehler wurde bereits behoben.

Voraussichtlich heute Abend erscheint WordPress 4.6.1, welches diese Änderung beinhaltet.

Ich schliesse deshalb dieses Issue vorneweg. Sollte der Fehler auch mit 4.6.1 nachwievor auftauchen, einfach nochmals melden.
