### ISSUE TITLE
Make plugin translatable

### ISSUE THREAD

**Issue by 00travelgirl00** [pluginkollektiv/2-Step-Verification#32]
At the moment the plugin is only available in german. I added the translation function into the plugin and creadet a .po-file. 

The File "form.html" contains strings, so I have renamed the file into form.php and also renamed the folder from html into mail. 

Pull Request: #31

**Comment by 2ndkauboy** [comment]
Very good! I can help by optimizing the loading of the mail template.

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
