### ISSUE TITLE
WooCommerce?

### ISSUE THREAD

**Issue by Martin597** [pluginkollektiv/2-Step-Verification#34]
Wenn ich das Plugin mit WooCommerce nutze, habe ich das Problem, dass auch die Kunden einen Code zugesendet bekommen, obwohl der gar nicht benötigt wird. Gibt es eine Möglichkeit, das so einzurichten, dass die 2-Faktor-Authentifizierung nur für Nutzer verschickt wird, die sich über /wp-admin/ einloggen? Oder evtl. eine andere Lösung, die sich für WooCommerce eignet?

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

There you can set this on a per user basis.

This plugin got no broader traction and will therefore be closed soon.
