### ISSUE TITLE
Separate E-Mail-Adresse für die Zusendung des Sicherheitscodes

### ISSUE THREAD

**Issue by sergejmueller** [pluginkollektiv/2-Step-Verification#4]
Der Nutzer muss/sollte die Möglichkeit bekommen, eine abweichende E-Mail-Adresse zu hinterlegen. An diese Adresse wird der Sicherheitscode verschickt. Auf diese Weise soll die Sicherheit erhöht und die Trennung zwischen System- und 2-Faktor-Mails erreicht werden.

Idee von [Christoph Daum](http://christoph-daum.de)

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
