### ISSUE TITLE
Gültigkeitsablauf des Sicherheitscodes via Plugin-Einstellung und Hook

### ISSUE THREAD

**Issue by sergejmueller** [pluginkollektiv/2-Step-Verification#5]
Die Zeitangabe in Minuten sollte in den Plugin-Einstellungen und via WordPress-Filter anpassbar sein.

Props [Sergej Müller](http://wpcoder.de)

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
