### ISSUE TITLE
User selber entscheiden lassen, ob er die zwei-faktor-authentifizierung nutzen möchte

### ISSUE THREAD

**Issue by PixelbarEupen** [pluginkollektiv/2-Step-Verification#7]
Die einzelnen User sollten über eine Checkbox o.Ä. selber entscheiden können, ob sie die Zwei-Faktor-Authentifizierung nutzen möchten oder nicht. Standardmäßig sollte die Authentifizierung auch bei jedem User abgeschaltet sein.

Warum? Installiert man das Plugin auf Seiten mit vielen registrierten Usern und das Plugin ist direkt scharf ist das für viele User schnell frustrierend, vor allem wenn die bei der Registrierung des Users genutzte E-Mail Adresse nicht mehr aktiv ist. Dann sind diese User erstmal von Ihrem Konto ausgeschlossen und müssen sich an den Admin wenden damit dieser deren hinterlegte E-Mail Adresse ändert.

Ausserdem will sicherlich nicht jeder User dieses System nutzen

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
