### ISSUE TITLE
Überarbeitung der Abfrageseite

### ISSUE THREAD

**Issue by sergejmueller** [pluginkollektiv/2-Step-Verification#8]
Die Seite für die Abfrage des Sicherheitscodes sollte überarbeitet werden. Folgende Punkte als Ziel:
- Lokalisierung der Texte
- Auslagerung von Inline-CSS in eine Datei
- Hooks für die Steuerung der Texte

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
