### ISSUE TITLE
Benutzerverwaltung bzw. Gruppensteuerung für die Zwei-Faktor-Authentifizierung

### ISSUE THREAD

**Issue by sergejmueller** [pluginkollektiv/2-Step-Verification#9]
Der Administrator sollte in der Lage sein, 2FA für bestimmte Nutzergruppen in WordPress freizuhalten bzw. abzustellen.

Props [Tobias Lambrecht](https://github.com/tobias-lambrecht)

**Comment by Zodiac1978** [comment]
There is an active feature plugin "Two Factor" which is providing the same feature set:
https://make.wordpress.org/core/features/
https://wordpress.org/plugins/two-factor/

This plugin got no broader traction and will therefore be closed soon.
